Add Key resource
Preskton/terraform-provider-twilio pull request #40
Opened 2019-12-21 22:03 UTC by flovouin

Hi,

I needed to create an API key for one of my projects and I stumbled upon this Terraform provider. The `API key` resource didn't exist so I added it. I used it in my project and it works fine. However I'm no Terraform nor Go expert, so it might be worth proofreading it.

Would you mind reviewing this diff, and consider merging it to this provider if you think it's relevant?

Cheers,

2019-12-22 23:39 UTC, Preskton commented
Hi, @flovouin - at first glance, this looks awesome! I will take a look this week and get things integrated in.

2019-12-22 23:42 UTC, Preskton requested changes
Looks great - requesting one somewhat minor change -- renaming the resource to `twilio_api_key` for clarity.

2019-12-22 23:42 UTC, Preskton commented on README.md
> +resource "twilio_key" "woomy" {
Do you mind updating to call the resource `twilio_api_key`?

2019-12-23 14:17 UTC, Preskton approved these changes
lgtm :tada:

2019-12-23 14:19 UTC, merged

2021-06-26 01:32 UTC, tedmiston commented
I wonder how easy / difficult it would be to extend this to support API keys for subaccounts?

2021-06-28 14:09 UTC, childish-sambino commented
@tedmiston We're launching the official provider soon to Pilot which includes this capability. See more at https://github.com/twilio/terraform-provider-twilio